Messages:
  CommandHelp: "%prefix% &3Command Help &8(&3Page &b%page% &8/ &b%pages%&8):"
  HelpFormat: "&8-&3] &3%help%&8: &b%command%"
  Reloaded: "%prefix% &3Configurations Reloaded!"
  PlayersOnly: "%prefix% &cPlayers Only!"
  NoPermission: "%prefix% &cYou Do Not Have Permission for That!"
  NightVision: "%prefix% &3Night Vision Added"
  InvalidCommand: "%prefix% &cInvalid Command!"
  TeleportedToSpawn: "%prefix% &3Teleported to Spawn"
  LobbyFull: "%prefix% &cThe Lobby for Map&8: &3%map% &8- &3is Full!"
  LobbyInvalid: "%prefix% &cInvalid Lobby!"
  LobbyLeave: "%prefix% &cLeft Lobby"