name: Population_Zero_Mod
main: com.trdwll.Game.initGame
version: 0.1
authors: [OhYea777,trdwll,parkbully]

commands:
   pzm:
      description: PZM

permissions:
  pzm.*:
    children:
      pzm.admin: true
      pzm.dev: true
  pzm.admin:
    children:
      pzm.player: true
      pzm.reload: true
    default: op
  pzm.donor:
    children:
      pzm.player: true
      pzm.join.force: true
  pzm.player:
    children:
      pzm.join: true
    default: true